// API ENDPOINTS
export const SUBGRAPH_LITE_ACCOUNT = import.meta.env.VITE_SUBGRAPH_LITE_ACCOUNT
export const SUBGRAPH_LITE_NAME = import.meta.env.VITE_SUBGRAPH_LITE_NAME
export const FEEDS_JSON_URL = import.meta.env.VITE_DATA_FEED_JSON_URL
